export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi",
  "Chandigarh",
  "Puducherry",
];

export const SUPPORTED_CITIES = [
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Pune",
  "Ahmedabad",
  "Jaipur",
  "Lucknow",
  "Noida",
  "Gurgaon",
  "Chandigarh",
  "Indore",
  "Nagpur",
  "Bhopal",
  "Kochi",
  "Coimbatore",
  "Visakhapatnam",
  "Thiruvananthapuram",
  "Surat",
  "Vadodara",
  "Ghaziabad",
  "Faridabad",
];

export const AMENITIES_LIST = [
  "Parking",
  "Gym",
  "Swimming Pool",
  "Garden",
  "Security",
  "Elevator",
  "Power Backup",
  "Water Supply",
  "Club House",
  "Playground",
];
